env:
  browser: true
  es6: true
extends: 'airbnb'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - jsx-a11y
  - react
rules:
    linebreak-style:
    - off
    jsx-a11y/href-no-hash:
    - off
    jsx-a11y/no-static-element-interactions:
    - off
    react/forbid-prop-types:
    - off
    react/jsx-filename-extension:
    - off
    react/jsx-no-bind:
    - off
    react/prop-types:
    - off
    react/prefer-stateless-function:
    - off
    semi:
    - off

