env:
  browser: true
  es6: true
extends: 'airbnb'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
rules:
    jsx-a11y/href-no-hash:
    - off
    react/jsx-filename-extension:
    - off
    react/jsx-no-bind:
    - off
    react/prefer-stateless-function:
    - off
    semi:
    - off

