sudo: required
dist: trusty
language: node_js
node_js:
  - "6"
cache:
    directories:
    - node_modules
    - $HOME/.yarn-cache
install:
- |
    yarn install
script:
- |
    yarn test
    node node_modules/eslint/bin/eslint src/**/*.js
    node node_modules/eslint/bin/eslint src/container/**/*.js
